import type { Metadata } from "next";
import "./globals.css";
import { SessionProviderWrapper } from '@/components/providers/SessionProviderWrapper';
import { Navbar } from "@/components/layout/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper>
          <Navbar />
          <main className="container py-6">
            {children}
          </main>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
